apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-service
  name: demo-service
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: demo-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: saiprasadkrishnamurthy/demo-service
          imagePullPolicy: Always
          ports:
            - name: liveness-port
              containerPort: 7000
          resources: #CHANGE
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi #256Mi
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: demo-service
  name: demo-service
  namespace: default
spec:
  ports:
    - # nodePort: 30702 #CHANGE
      port: 7000 #CHANGE
      protocol: TCP
      targetPort: 7000 #CHANGE
  selector:
    app: demo-service
  sessionAffinity: None #CHANGE
  type: LoadBalancer