apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  type: NodePort
  ports:
  - port: 7000
    protocol: TCP
    name: http
  selector:
    app: demo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  selector:
    matchLabels:
      app: demo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
      - name: demo-service
        image: saiprasadkrishnamurthy/demo-service/demo-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: demo-service-config-0.0.1-snapshot
        ports:
        - containerPort: 7000
        volumeMounts:
        - mountPath: /tmp
          name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          path: /tmp
          type: Directory
      imagePullSecrets:
      - name: docker-registry-credentials-secret

